validate maximum length of account number and bank blocks
thenewboston-developers/Validator pull request #132
Opened 2020-12-24 15:49 UTC by JonSchapiro

2020-12-24 18:04 UTC, shahraizali commented
Hey @JonSchapiro  Are these test cases working for you locally?

2020-12-24 18:11 UTC, JonSchapiro commented
> Hey @JonSchapiro Are these test cases working for you locally?

@shahraizali my second test now works. However, it seems that the validator is not working on the query param while asking for an account by account_number?

2020-12-24 18:18 UTC, shahraizali commented
okay, btw if don't know already. you can run the tests locally as well so you don't have to push to test. I am judging from multiple commits.

2020-12-24 18:20 UTC, JonSchapiro commented
> okay, btw if don't know already. you can run the tests locally as well so you don't have to push to test. I am judging from multiple commits.

yes, apologies. I realized that now and can run them locally.

2020-12-24 18:23 UTC, shahraizali commented
> yes, apologies.

No worries. have at it, try to debug the issue now that you can run it locally. make sure you are pinging the correct endpoint and also make sure you are sending the account number along in the expected and correct way. You can update here or in the channel with your findings.

2020-12-24 21:10 UTC, JonSchapiro commented
https://github.com/thenewboston-developers/Validator/issues/124

2020-12-30 16:52 UTC, JonSchapiro commented
@shahraizali could I have a review on this please :)?

2020-12-30 19:00 UTC, shahraizali approved these changes

2020-12-30 19:30 UTC, vosi approved these changes

2021-01-02 16:19 UTC, JonSchapiro commented
@vosi @shahraizali can this be merged?

2021-01-07 13:11 UTC, JonSchapiro commented
@shahraizali @vosi just checking in again to see if someone can merge?

2021-01-07 15:59 UTC, vosi requested changes

2021-01-07 15:59 UTC, vosi commented on v1/accounts/factories/account.py
> +    account_number = Faker('pystr', max_chars=VERIFY_KEY_LENGTH - 1)
why -1?

2021-01-07 15:59 UTC, vosi commented on v1/accounts/views/account.py
> +            return Response({'balance': None}, status=status.HTTP_401_UNAUTHORIZED)
why 401?

2021-01-07 15:59 UTC, vosi commented on v1/accounts/views/account.py
> +        if account_number is not None and len(account_number) >= VERIFY_KEY_LENGTH:
>= ? 64 is ok if I'm not mistaking.

2021-01-16 21:00 UTC, buckyroberts commented
Closing due to inactivity. Want to allow another contributors to work on these tests.

2021-01-16 21:00 UTC, closed without merging