Fix Flake8 . issues #91
thenewboston-developers/Validator pull request #94
Opened 2020-11-23 03:46 UTC by AbhayAysola

Fixes #91

2020-11-23 13:56 UTC, vosi requested changes

2020-11-23 13:56 UTC, vosi commented on v1/self_configurations/management/commands/initialize_test_confirmation_validator.py
> +    _help = 'Delete existing data, load in fixture data, set self as confirmation validator, rebuild cache'
you should keep `help` here and add `noqa` rule since it's Django's issue

2020-11-23 13:56 UTC, vosi commented on v1/self_configurations/management/commands/initialize_test_primary_validator.py
> +    _help = 'Delete existing data, load in fixture data, set self as primary validator, rebuild cache'
same help issue

2020-11-23 13:56 UTC, vosi commented on v1/self_configurations/management/commands/initialize_validator.py
> +    _help = 'Initialize validator'
same help issue

2020-11-23 13:56 UTC, vosi commented on v1/self_configurations/management/commands/set_primary_validator.py
> +    _help = 'Fetch config from PV, create related Validator, set that Validator as the primary validator'
same help issue

2020-11-23 14:01 UTC, vosi requested changes

2020-11-23 14:02 UTC, vosi requested changes
@AbhayAysola additionally, the task is to uncomment https://github.com/thenewboston-developers/Validator/blob/master/.github/workflows/pr.yml#L45 that 2 lines

2020-11-23 15:36 UTC, AbhayAysola commented
@vosi Thanks for helping me get this right. I've made all the changes you requested. Let me know if I've done anything wrong, or if there are other changes to be made. Thanks again for your help :)

2020-11-23 16:04 UTC, vosi commented
@AbhayAysola one more thing, do not use plain `noqa`, please define a rule that should be ignored, like you did for `import *`

2020-11-24 01:49 UTC, AbhayAysola commented
> @AbhayAysola one more thing, do not use plain `noqa`, please define a rule that should be ignored, like you did for `import *`

Sure, I will do that.

2020-11-24 14:57 UTC, vosi approved these changes

2020-11-24 15:01 UTC, vosi requested changes

2020-11-24 15:03 UTC, vosi commented
@AbhayAysola i still can't accept it,
1. check my change request
2. check the ticket description again and uncomment 2 lines is the file

2020-11-25 01:47 UTC, AbhayAysola commented
> @AbhayAysola i still can't accept it,
> 
> 1. check my change request
> 2. check the ticket description again and uncomment 2 lines is the file

My bad, I messed up with commits and stuff and I thought I had made those changes but I didn't. 😓 
Should be good now.

2020-11-25 02:40 UTC, AbhayAysola commented
@vosi Do you have any idea why flake8 thinks there's an import in line 4 of update_stack.py ? I don't understand why the checks are failing.

2020-11-25 14:38 UTC, vosi commented
> @vosi Do you have any idea why flake8 thinks there's an import in line 4 of update_stack.py ? I don't understand why the checks are failing.

right now it's configured to merge branches to master internally to do flake test on a merged branch ... I might change that later ... or not 
but as a quick fix, I'd suggest you rebasing or updating your branch with upstream

2020-11-27 01:26 UTC, AbhayAysola commented
Ok, should be working by now.

2020-11-27 12:36 UTC, vosi approved these changes

2020-11-27 12:37 UTC, merged

2020-11-27 18:32 UTC, odetolataiwo commented
paid